name: Keep Streamlit App Alive

on:
  schedule:
    - cron: "0 */12 * * *"   # Cada 12 horas
  workflow_dispatch:          # Permite ejecutarlo manualmente

jobs:
  ping-app:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Streamlit App
        run: |
          echo "Pinging Streamlit app..."
          curl -s -o /dev/null -w "%{http_code}\n" https://radar-oportunidades.streamlit.app/
